<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>


        <!-- Package Configuration -->
        <PackageId>DevMuhsener.Shared.Emails</PackageId>
        <Version>1.0.0</Version>
        <Authors>devmuhsener</Authors>
        <Company>yetenek.ai</Company>
        <Description>A helpful library built on .NET 10</Description>
        <PackageTags>dotnet10;utility</PackageTags>
        <PackageOutputPath>$(HOME)/LocalNuGet</PackageOutputPath>

        <!-- Generate the .nupkg file every time you build -->
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

<!--    <ItemGroup>-->
<!--        <ProjectReference Include="..\Shared.Core\Shared.Core.csproj"/>-->
<!--    </ItemGroup>-->

    <ItemGroup>
        <PackageReference Include="DevMuhsener.Shared.Core" Version="1.0.0" />
        <PackageReference Include="Fluid.Core" Version="2.31.0"/>
        <PackageReference Include="MailKit" Version="4.17.0"/>
    </ItemGroup>

</Project>
